### ISSUE TITLE
How can you execute it?

### ISSUE THREAD

**Issue by DebugBios** [Ochii/cso2-master-services#1]
![1](https://user-images.githubusercontent.com/44349391/57275631-14767600-70da-11e9-84dc-3786aacc3385.PNG)
![2](https://user-images.githubusercontent.com/44349391/57275632-14767600-70da-11e9-8c05-fb80fdb8ba1f.PNG)
![3](https://user-images.githubusercontent.com/44349391/57275633-14767600-70da-11e9-9c9c-e5731f3fda44.PNG)
![4](https://user-images.githubusercontent.com/44349391/57275635-150f0c80-70da-11e9-9c20-86227db070a7.PNG)
![5](https://user-images.githubusercontent.com/44349391/57275645-1cceb100-70da-11e9-8d1f-4518216ee091.PNG)

I don't know how to install it.

**Comment by Ochii** [comment]
you need to install docker and docker-compose

**Comment by DebugBios** [comment]
![1](https://user-images.githubusercontent.com/44349391/57343093-dd0cd580-717c-11e9-98a7-7e936b13b1df.PNG)
Can you tell me what's wrong?

**Comment by DebugBios** [comment]
![1](https://user-images.githubusercontent.com/44349391/57346581-fd8f5c80-7189-11e9-9247-bc3f0f3e68fd.PNG)

**Comment by DebugBios** [comment]
![캡처](https://user-images.githubusercontent.com/44349391/57398733-b4332180-720a-11e9-9b2e-87214fa77bc4.PNG)
?

**Comment by DebugBios** [comment]
![캡처](https://user-images.githubusercontent.com/44349391/57398794-d3ca4a00-720a-11e9-8dad-17518e3d70a2.PNG)

**Comment by DebugBios** [comment]
![캡처](https://user-images.githubusercontent.com/44349391/57398814-db89ee80-720a-11e9-943e-09fdf199b4e3.PNG)
What is the problem? The gulp build is not working

**Comment by DebugBios** [comment]
![캡처](https://user-images.githubusercontent.com/44349391/57399002-53f0af80-720b-11e9-92c0-49ae1ee38a1f.PNG)
What's wrong with this?
The gulp build is not working

**Comment by DebugBios** [comment]
![캡처](https://user-images.githubusercontent.com/44349391/57399050-77b3f580-720b-11e9-8005-e92bc0862846.PNG)
What's wrong with this?
The gulp build is not working

**Comment by DebugBios** [comment]
![1](https://user-images.githubusercontent.com/44349391/57403286-53a8e200-7214-11e9-9683-899d88b66f5a.PNG)

**Comment by DebugBios** [comment]
![1](https://user-images.githubusercontent.com/44349391/57505063-e68b6e80-7331-11e9-86ad-c0778580910e.PNG)

**Comment by DebugBios** [comment]
Do I have to install mongodb?

**Comment by Ochii** [comment]
> Do I have to install mongodb?

It's included in the docker-compose configuration. The configuration tells docker-compose to download MongoDB, Consul and Registrator containers

**Comment by DebugBios** [comment]
ERROR: Service 'master-server' failed to build: Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection (Client.Timeout exceeded while awaiting headers)

I'm sorry but I don't know how to solve this.

**Comment by Ochii** [comment]
> Get https://registry-1.docker.io/v2/: net/http: request canceled while waiting for connection

Is your server behind a proxy?

**Comment by DebugBios** [comment]
Are you saying this? I don't use a proxy
![1](https://user-images.githubusercontent.com/44349391/57533436-b9ae7a00-7378-11e9-8305-c9ac1931c18c.PNG)

**Comment by Ochii** [comment]
Maybe try https://stackoverflow.com/questions/48056365/error-get-https-registry-1-docker-io-v2-net-http-request-canceled-while-b or https://forums.docker.com/t/error-response-from-daemon-get-https-registry-1-docker-io-v2/23741

**Comment by DebugBios** [comment]
Building master-server
Step 1/10 : FROM node:11
ERROR: Service 'master-server' failed to build: Get https://registry-1.docker.io/v2/library/node/manifests/11: unauthorized: incorrect username or password

What else is wrong with this?

**Comment by Ochii** [comment]
> Building master-server
> Step 1/10 : FROM node:11
> ERROR: Service 'master-server' failed to build: Get https://registry-1.docker.io/v2/library/node/manifests/11: unauthorized: incorrect username or password
> 
> What else is wrong with this?

```cd``` to the master services directory and ```docker-compose up -d``` again

**Comment by DebugBios** [comment]
![1](https://user-images.githubusercontent.com/44349391/57534740-a94bce80-737b-11e9-9266-302f61ce780c.PNG)
I think I am very stupid.

Can you help me with a discode or a team viewer?
