### ISSUE TITLE
cso2-master-services

### ISSUE THREAD

**Issue by tlsdlftn252** [Ochii/cso2-master-services#33]
Server Construction method Let me know.

**Comment by IGNRexI** [comment]
+1

**Comment by lateleite** [comment]
I don't know if I understand your question, are you asking for a server setup guide?

**Comment by tlsdlftn252** [comment]
![Screenshot_20200127-232557](https://user-images.githubusercontent.com/60119021/73182458-73928400-415c-11ea-8ca5-d8df461b6321.png)

**Comment by IGNRexI** [comment]
For which location will you open the server ? @tlsdlftn252
